prj_MVC_core/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using prj_MVC_core.Models;
using prj_MVC_core.ViewModels;
using System.Collections.Generic;

namespace prj_MVC_core.Controllers
{
    public class CustomerController : Controller
    {

        public IActionResult test03()
        {

            TCustomer x = new TCustomer();
            x.FName = "Test03";
            x.FPhone = "Test03";
            CMyClass CC = new CMyClass(x);
            CC.customer1 = x;
            CC.insert3();
            return View();
        }

        public IActionResult test() 
        {
            
            TCustomer x = new TCustomer();
            x.FName= "Test";
            x.FPhone = "09xxxxx";           
            CMyClass CC = new CMyClass(x);
            CC.customer1 = x;
            CC.insert3();
            return View();
        }
        public IActionResult List(CKeywordViewModel vm)
        {
            DbdemoContext db = new DbdemoContext();
            //新版不提供Request回傳資料，所以透過ViewModel將資料儲存後回傳
            string keyword = vm.txtKeyword;
            IEnumerable<TCustomer> datas = null;
            if (string.IsNullOrEmpty(keyword))
                datas = from t in db.TCustomers select t;
            else
                datas = db.TCustomers.Where(c => c.FName.Contains(keyword) || c.FPhone.Contains(keyword) || c.FEmail.Contains(keyword) || c.FAddress.Contains(keyword));

            List<CCustomerWrap> list = new List<CCustomerWrap>();
            foreach (var item in datas)
            { 
                list.Add(new CCustomerWrap() { customer = item });
            }
               
            return View(list);            
        }

        public IActionResult Create()
        {            
            return View();
        }

        [HttpPost]
        public IActionResult Create(TCustomer customer)
        {
            DbdemoContext db = new DbdemoContext();
            db.TCustomers.Add(customer);
            db.SaveChanges();
            return RedirectToAction("List");
        }

     
        public IActionResult Delete(int? id)
        {
            if (id != null)
            {
                DbdemoContext db = new DbdemoContext();
                TCustomer customer = db.TCustomers.FirstOrDefault(c => c.Fid == id);
                if (customer != null)
                {
                    db.TCustomers.Remove(customer);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List");

            DbdemoContext db = new DbdemoContext();
            IEnumerable<TCustomer> datas = null;
            TCustomer customer = db.TCustomers.FirstOrDefault(c => c.Fid == id);
            if (customer == null)
                return RedirectToAction("List");                 

           
          

            return View(new CCustomerWrap() { customer = customer });
        }


        [HttpPost]
        public IActionResult Edit(CCustomerWrap C)
        {
            DbdemoContext db = new DbdemoContext();
            TCustomer customer = db.TCustomers.FirstOrDefault(cs => cs.Fid == C.Fid);
            if (customer != null)
            {
                customer.FName = C.FName;
                customer.FPhone = C.FPhone;
                customer.FEmail = C.FEmail;
                customer.FAddress = C.FAddress;
                customer.FPassword = C.FPassword;
                
                db.SaveChanges();
            }

            return RedirectToAction("List");
        }
       
      

    }
}

prj_MVC_core/Controllers/PhotoController.cs
using Microsoft.AspNetCore.Mvc;
using prj_MVC_core.Models;
using prj_MVC_core.ViewModels;
using System.Text.Json;

namespace prj_MVC_core.Controllers
{
    public class PhotoController : Controller
    {
        IWebHostEnvironment _env = null;
        public PhotoController(IWebHostEnvironment IHE) 
        {
           _env= IHE;
        }



        public IActionResult List(CKeywordViewModel vm)
        {
            if(!HttpContext.Session.Keys.Contains(CDictionary.SK_LOGEDIN_USER))
                return RedirectToAction("Login","Home");

            string json = HttpContext.Session.GetString(CDictionary.SK_LOGEDIN_USER);
            TCustomer customer = JsonSerializer.Deserialize<TCustomer>(json);

            DbdemoContext db = new DbdemoContext();
            //新版不提供Request回傳資料，所以透過ViewModel將資料儲存後回傳
            string keyword = vm.txtKeyword;
            IEnumerable<TPhoto> datas = null;
            if (string.IsNullOrEmpty(keyword))
                datas = from t in db.TPhotos 
                        where t.FOwnerId == customer.Fid
                        select t;
            else
                datas = db.TPhotos.Where(c => c.FDescription.Contains(keyword) && c.FOwnerId==customer.Fid); 

            List<CPhotoWrap> list = new List<CPhotoWrap>();
            foreach (var item in datas)
            {
                list.Add(new CPhotoWrap() { photo = item });
            }

            return View(list);            
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CPhotoWrap photo)
        {
            if (!HttpContext.Session.Keys.Contains(CDictionary.SK_LOGEDIN_USER))
                return RedirectToAction("List");
            string json = HttpContext.Session.GetString(CDictionary.SK_LOGEDIN_USER);
            TCustomer customer = JsonSerializer.Deserialize<TCustomer>(json);
            if (photo.photoPath != null)
            {
                string photoName = Guid.NewGuid().ToString() + ".jpg";
                photo.FImage = photoName;
                photo.photoPath.CopyTo(new FileStream(_env.WebRootPath+"/imgs/" + photoName,FileMode.Create));
            }
            DbdemoContext db = new DbdemoContext();
            photo.FDate = DateTime.Now.ToString("yyyyMMddHHmmss");
            photo.FOwnerId = customer.Fid;
            db.TPhotos.Add(photo.photo);
            db.SaveChanges();
            return RedirectToAction("List");
        }

        public ActionResult Delete(int? id)
        {
            if (id != null)
            {
                DbdemoContext db = new DbdemoContext();
                TPhoto photo = db.TPhotos.FirstOrDefault(t => t.Fid == id);
                if (photo != null)
                {
                    db.TPhotos.Remove(photo);
                    db.SaveChanges();
                }
            }
            return RedirectToAction("List");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return RedirectToAction("List");
            DbdemoContext db = new DbdemoContext();
            TPhoto photo = db.TPhotos.FirstOrDefault(p => p.Fid == id);
            if (photo == null)
                return RedirectToAction("List");

            return View(new CPhotoWrap() { photo=photo});
        }

        [HttpPost]
        public ActionResult Edit(CPhotoWrap p)
        {
            DbdemoContext db = new DbdemoContext();
            TPhoto photo = db.TPhotos.FirstOrDefault(c => c.Fid == p.Fid);
            if (photo != null)
            {
                photo.FDescription = photo.FDescription;              
                photo.FImage = photo.FImage;
                db.SaveChanges();
            }
            return RedirectToAction("List");
        }
    }
}

prj_MVC_core/Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Hosting;
using prj_MVC_core.Models;
using System.Text.Json;

namespace prj_MVC_core.Controllers
{
    public class PostController : Controller
    {
        public IActionResult List()
        {
            DbdemoContext db = new DbdemoContext();
            var customers= from c in db.TCustomers select c;
            
            db = new DbdemoContext();
            var datas = from t in db.TPhotos                   
                        select t;

            List<CPhotoWrap> list = new List<CPhotoWrap>();
            foreach (var data in datas) 
            {
                CPhotoWrap P =(new CPhotoWrap() { photo = data });
                TCustomer C = customers.FirstOrDefault(c=>c.Fid== data.FOwnerId);
                if (C != null) 
                {
                    P.postUser = C;                 
                }
                list.Add(P);
            }
            return View(list);
        }

        public IActionResult AddComment() 
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddComment(Tcomment C)
        {
            string json = HttpContext.Session.GetString(CDictionary.SK_LOGEDIN_USER);
            TCustomer user =JsonSerializer.Deserialize<TCustomer>(json);
            C.FPost = HttpContext.Session.GetInt32(CDictionary.SK_CURRENT_POSTID);
            C.FUserId = user.Fid;
            C.FDate = DateTime.Now.ToString("yyyyMMddHHmmss");
            DbdemoContext db = new DbdemoContext();
            db.Tcomments.Add(C);
            db.SaveChanges();
            return RedirectToAction("Reply",new { id=C.FPost});

        }

        public IActionResult Reply(int id) 
        {
            HttpContext.Session.SetInt32(CDictionary.SK_CURRENT_POSTID,(int)id);
            TPhoto photo = (new DbdemoContext()).TPhotos.FirstOrDefault(p=>p.Fid ==id);
            if(photo == null) 
                return RedirectToAction("List");            
            ViewBag.PHOTO = photo.FImage;
            ViewBag.DESC = photo.FDescription;
            DbdemoContext db = new DbdemoContext();
            var post =(new DbdemoContext()).Tcomments.Where(c=>c.FPost==id);
            return View(post);
        }
    }
}

prj_MVC_core/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - prj_MVC_core</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/prj_MVC_core.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">prj_MVC_core</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Customer" asp-action="List">會員資料</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Photo" asp-action="List">照片</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="List">評論</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container-fluid mx-3">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - prj_MVC_core - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>